In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

In [2]:
main_path = "./../cleaned_data/surveys/"

phq9 = pd.read_csv(f"{main_path}clean_PHQ-9.csv")

In [3]:
# Clean column names: remove commas, lowercase everything, replace spaces with underscores
phq9.columns = (
    phq9.columns.str.replace(",", "", regex=False)  # remove commas
    .str.replace(".", "", regex=False)  # remove periods
    .str.strip()  # remove leading/trailing whitespace
    .str.lower()  # lowercase
    .str.replace(" ", "_")  # replace spaces with underscores
)

for x in phq9.columns:
    print(x)

uid
type
little_interest_or_pleasure_in_doing_things
feeling_down_depressed_hopeless
trouble_falling_or_staying_asleep_or_sleeping_too_much
feeling_tired_or_having_little_energy
poor_appetite_or_overeating
feeling_bad_about_yourself_or_that_you_are_a_failure_or_have_let_yourself_or_your_family_down
trouble_concentrating_on_things_such_as_reading_the_newspaper_or_watching_television
moving_or_speaking_so_slowly_that_other_people_could_have_noticed_or_the_opposite_being_so_figety_or_restless_that_you_have_been_moving_around_a_lot_more_than_usual
thoughts_that_you_would_be_better_off_dead_or_of_hurting_yourself
response
total_score
depression_severity

In [4]:
print(phq9.head(2))

   uid type  little_interest_or_pleasure_in_doing_things  \
0  u00  pre                                            0
1  u01  pre                                            1

   feeling_down_depressed_hopeless  \
0                                1
1                                1

   trouble_falling_or_staying_asleep_or_sleeping_too_much  \
0                                                  0
1                                                  1

   feeling_tired_or_having_little_energy  poor_appetite_or_overeating  \
0                                      1                            0
1                                      1                            0

   feeling_bad_about_yourself_or_that_you_are_a_failure_or_have_let_yourself_or_your_family_down  \
0                                                  0
1                                                  1

   trouble_concentrating_on_things_such_as_reading_the_newspaper_or_watching_television  \
0                                                  0
1                                                  0

   moving_or_speaking_so_slowly_that_other_people_could_have_noticed_or_the_opposite_being_so_figety_or_restless_that_you_have_been_moving_around_a_lot_more_than_usual  \
0                                                  0
1                                                  0

   thoughts_that_you_would_be_better_off_dead_or_of_hurting_yourself  \
0                                                  0
1                                                  0

   response  total_score depression_severity
0         0            2  Minimal depression
1         2            5     Mild depression

In [5]:
# Segregating to pre and post into different files
phq9_pre = phq9[phq9["type"] == "pre"].copy()
phq9_post = phq9[phq9["type"] == "post"].copy()

# Drop the 'type' column safely
phq9_pre.drop("type", axis=1, inplace=True)
phq9_post.drop("type", axis=1, inplace=True)

# Add 'pre_' prefix to all columns except 'uid'
phq9_pre = phq9_pre.rename(
    columns={col: f"pre_{col}" for col in phq9_pre.columns if col != "uid"}
)

# Add 'post_' prefix to all columns except 'uid'
phq9_post = phq9_post.rename(
    columns={col: f"post_{col}" for col in phq9_post.columns if col != "uid"}
)

phq9_transformed = pd.merge(phq9_pre, phq9_post, on="uid", how="inner")

In [6]:
print(phq9_transformed.head(2))
print(phq9_post.head(2))
print(phq9_pre.head(2))

   uid  pre_little_interest_or_pleasure_in_doing_things  \
0  u00                                                0
1  u01                                                1

   pre_feeling_down_depressed_hopeless  \
0                                    1
1                                    1

   pre_trouble_falling_or_staying_asleep_or_sleeping_too_much  \
0                                                  0
1                                                  1

   pre_feeling_tired_or_having_little_energy  pre_poor_appetite_or_overeating  \
0                                          1                                0
1                                          1                                0

   pre_feeling_bad_about_yourself_or_that_you_are_a_failure_or_have_let_yourself_or_your_family_down  \
0                                                  0
1                                                  1

   pre_trouble_concentrating_on_things_such_as_reading_the_newspaper_or_watching_television  \
0                                                  0
1                                                  0

   pre_moving_or_speaking_so_slowly_that_other_people_could_have_noticed_or_the_opposite_being_so_figety_or_restless_that_you_have_been_moving_around_a_lot_more_than_usual  \
0                                                  0
1                                                  0

   pre_thoughts_that_you_would_be_better_off_dead_or_of_hurting_yourself  \
0                                                  0
1                                                  0

   pre_response  pre_total_score pre_depression_severity  \
0             0                2      Minimal depression
1             2                5         Mild depression

   post_little_interest_or_pleasure_in_doing_things  \
0                                                 0
1                                                 0

   post_feeling_down_depressed_hopeless  \
0                                     0
1                                     1

   post_trouble_falling_or_staying_asleep_or_sleeping_too_much  \
0                                                  0
1                                                  1

   post_feeling_tired_or_having_little_energy  \
0                                           1
1                                           1

   post_poor_appetite_or_overeating  \
0                                 0
1                                 0

   post_feeling_bad_about_yourself_or_that_you_are_a_failure_or_have_let_yourself_or_your_family_down  \
0                                                  1
1                                                  0

   post_trouble_concentrating_on_things_such_as_reading_the_newspaper_or_watching_television  \
0                                                  1
1                                                  0

   post_moving_or_speaking_so_slowly_that_other_people_could_have_noticed_or_the_opposite_being_so_figety_or_restless_that_you_have_been_moving_around_a_lot_more_than_usual  \
0                                                  0
1                                                  1

   post_thoughts_that_you_would_be_better_off_dead_or_of_hurting_yourself  \
0                                                  0
1                                                  0

   post_response  post_total_score post_depression_severity
0              1                 3       Minimal depression
1              1                 4       Minimal depression
    uid  post_little_interest_or_pleasure_in_doing_things  \
46  u00                                                 0
47  u01                                                 0

    post_feeling_down_depressed_hopeless  \
46                                     0
47                                     1

    post_trouble_falling_or_staying_asleep_or_sleeping_too_much  \
46                                                  0
47                                                  1

    post_feeling_tired_or_having_little_energy  \
46                                           1
47                                           1

    post_poor_appetite_or_overeating  \
46                                 0
47                                 0

    post_feeling_bad_about_yourself_or_that_you_are_a_failure_or_have_let_yourself_or_your_family_down  \
46                                                  1
47                                                  0

    post_trouble_concentrating_on_things_such_as_reading_the_newspaper_or_watching_television  \
46                                                  1
47                                                  0

    post_moving_or_speaking_so_slowly_that_other_people_could_have_noticed_or_the_opposite_being_so_figety_or_restless_that_you_have_been_moving_around_a_lot_more_than_usual  \
46                                                  0
47                                                  1

    post_thoughts_that_you_would_be_better_off_dead_or_of_hurting_yourself  \
46                                                  0
47                                                  0

    post_response  post_total_score post_depression_severity
46              1                 3       Minimal depression
47              1                 4       Minimal depression
   uid  pre_little_interest_or_pleasure_in_doing_things  \
0  u00                                                0
1  u01                                                1

   pre_feeling_down_depressed_hopeless  \
0                                    1
1                                    1

   pre_trouble_falling_or_staying_asleep_or_sleeping_too_much  \
0                                                  0
1                                                  1

   pre_feeling_tired_or_having_little_energy  pre_poor_appetite_or_overeating  \
0                                          1                                0
1                                          1                                0

   pre_feeling_bad_about_yourself_or_that_you_are_a_failure_or_have_let_yourself_or_your_family_down  \
0                                                  0
1                                                  1

   pre_trouble_concentrating_on_things_such_as_reading_the_newspaper_or_watching_television  \
0                                                  0
1                                                  0

   pre_moving_or_speaking_so_slowly_that_other_people_could_have_noticed_or_the_opposite_being_so_figety_or_restless_that_you_have_been_moving_around_a_lot_more_than_usual  \
0                                                  0
1                                                  0

   pre_thoughts_that_you_would_be_better_off_dead_or_of_hurting_yourself  \
0                                                  0
1                                                  0

   pre_response  pre_total_score pre_depression_severity
0             0                2      Minimal depression
1             2                5         Mild depression

## Map labels

In [7]:
severity_map = {
    "Minimal depression": 0,
    "Mild depression": 1,
    "Moderate depression": 2,
    "Moderately severe depression": 3,
    "Severe depression": 4,
}

phq9_post["post_depression_class"] = phq9_post["post_depression_severity"].map(
    severity_map
)
phq9_pre["pre_depression_class"] = phq9_pre["pre_depression_severity"].map(severity_map)
phq9_transformed["pre_depression_class"] = phq9_transformed[
    "pre_depression_severity"
].map(severity_map)
phq9_transformed["post_depression_class"] = phq9_transformed[
    "post_depression_severity"
].map(severity_map)

In [8]:
display(phq9_post)
display(phq9_pre)
display(phq9_transformed)

,uid,post_little_interest_or_pleasure_in_doing_things,post_feeling_down_depressed_hopeless,post_trouble_falling_or_staying_asleep_or_sleeping_too_much,post_feeling_tired_or_having_little_energy,post_poor_appetite_or_overeating,post_feeling_bad_about_yourself_or_that_you_are_a_failure_or_have_let_yourself_or_your_family_down,post_trouble_concentrating_on_things_such_as_reading_the_newspaper_or_watching_television,post_moving_or_speaking_so_slowly_that_other_people_could_have_noticed_or_the_opposite_being_so_figety_or_restless_that_you_have_been_moving_around_a_lot_more_than_usual,post_thoughts_that_you_would_be_better_off_dead_or_of_hurting_yourself,post_response,post_total_score,post_depression_severity,post_depression_class
46,u00,0,0,0,1,0,1,1,0,0,1,3,Minimal depression,0.0
47,u01,0,1,1,1,0,0,0,1,0,1,4,Minimal depression,0.0
48,u02,2,0,0,1,1,0,1,0,0,1,5,Mild depression,1.0
49,u03,1,1,0,1,0,1,0,0,0,1,4,Minimal depression,0.0
50,u04,1,1,1,1,1,2,1,0,0,1,8,Mild depression,1.0
51,u05,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
52,u07,1,1,2,2,2,0,0,0,0,1,8,Mild depression,1.0
53,u09,0,0,0,0,1,1,0,0,0,0,2,Minimal depression,0.0
54,u10,0,0,0,1,1,0,0,2,0,0,4,Minimal depression,0.0
55,u14,0,0,1,1,1,0,0,0,0,-1,3,Minimal depression,0.0
56,u15,0,0,1,0,0,0,0,0,0,0,1,Minimal depression,0.0
57,u16,1,2,2,3,2,2,0,0,0,1,12,Moderate depression,2.0
58,u17,2,2,3,3,2,3,3,0,0,1,18,Moderately severe depression,3.0
59,u18,2,2,1,2,2,1,1,0,1,1,12,Moderate depression,2.0
60,u19,0,1,0,0,1,1,0,0,1,0,4,Minimal depression,0.0
61,u20,1,2,1,1,1,2,0,0,0,1,8,Mild depression,1.0
62,u23,2,3,3,2,2,3,2,2,2,2,21,Severe depression,4.0
63,u24,2,1,0,1,1,1,1,0,0,1,7,Mild depression,1.0
64,u27,1,1,0,2,0,1,2,0,0,1,7,Mild depression,1.0
65,u30,0,0,0,0,0,0,0,0,0,-1,0,NaN,NaN
66,u31,3,0,0,0,0,0,1,1,0,0,5,Mild depression,1.0
67,u32,0,0,1,1,0,0,0,0,0,0,2,Minimal depression,0.0
68,u33,3,3,3,3,3,3,3,3,1,3,25,Severe depression,4.0
69,u34,1,0,1,1,1,0,2,0,0,0,6,Mild depression,1.0
70,u35,1,1,0,1,1,1,1,1,0,0,7,Mild depression,1.0
71,u36,0,0,0,1,0,0,0,0,0,1,1,Minimal depression,0.0
72,u42,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
73,u43,0,0,1,1,1,0,1,0,0,1,4,Minimal depression,0.0
74,u44,1,0,0,1,0,0,0,0,0,1,2,Minimal depression,0.0
75,u45,0,0,1,0,0,0,1,0,0,0,2,Minimal depression,0.0
76,u47,0,0,0,0,0,0,0,1,0,0,1,Minimal depression,0.0
77,u49,3,0,2,2,1,0,0,0,0,1,8,Mild depression,1.0
78,u51,0,0,0,0,0,0,0,0,0,-1,0,NaN,NaN
79,u52,1,3,3,2,3,1,0,1,1,3,15,Moderately severe depression,3.0
80,u53,0,1,3,2,3,0,2,0,0,1,11,Moderate depression,2.0
81,u56,0,0,0,2,0,0,1,0,0,1,3,Minimal depression,0.0
82,u58,0,1,0,2,2,1,1,1,0,0,8,Mild depression,1.0
83,u59,0,0,2,2,1,0,1,1,0,1,7,Mild depression,1.0

,uid,pre_little_interest_or_pleasure_in_doing_things,pre_feeling_down_depressed_hopeless,pre_trouble_falling_or_staying_asleep_or_sleeping_too_much,pre_feeling_tired_or_having_little_energy,pre_poor_appetite_or_overeating,pre_feeling_bad_about_yourself_or_that_you_are_a_failure_or_have_let_yourself_or_your_family_down,pre_trouble_concentrating_on_things_such_as_reading_the_newspaper_or_watching_television,pre_moving_or_speaking_so_slowly_that_other_people_could_have_noticed_or_the_opposite_being_so_figety_or_restless_that_you_have_been_moving_around_a_lot_more_than_usual,pre_thoughts_that_you_would_be_better_off_dead_or_of_hurting_yourself,pre_response,pre_total_score,pre_depression_severity,pre_depression_class
0,u00,0,1,0,1,0,0,0,0,0,0,2,Minimal depression,0.0
1,u01,1,1,1,1,0,1,0,0,0,2,5,Mild depression,1.0
2,u02,2,1,2,2,2,1,1,2,0,1,13,Moderate depression,2.0
3,u03,0,1,0,0,0,0,0,1,0,1,2,Minimal depression,0.0
4,u04,1,1,0,1,1,1,1,0,0,1,6,Mild depression,1.0
5,u05,0,0,1,0,1,0,0,0,0,-1,2,Minimal depression,0.0
6,u07,1,1,0,1,2,1,1,0,0,0,7,Mild depression,1.0
7,u08,1,1,0,0,1,1,1,0,0,0,5,Mild depression,1.0
8,u09,0,0,1,1,1,0,1,0,0,0,4,Minimal depression,0.0
9,u10,0,0,0,0,0,0,0,0,0,-1,0,NaN,NaN
10,u12,0,0,0,1,0,0,0,0,0,0,1,Minimal depression,0.0
11,u13,0,1,0,1,1,1,0,0,0,0,4,Minimal depression,0.0
12,u14,0,0,0,1,0,0,0,0,0,0,1,Minimal depression,0.0
13,u15,1,0,0,1,1,0,0,0,0,0,3,Minimal depression,0.0
14,u16,1,1,1,0,0,3,0,0,0,1,6,Mild depression,1.0
15,u17,1,1,3,3,3,1,0,1,0,1,13,Moderate depression,2.0
16,u18,2,2,1,2,2,3,1,0,2,2,15,Moderately severe depression,3.0
17,u19,1,1,0,0,1,1,0,0,1,1,5,Mild depression,1.0
18,u20,1,1,1,1,1,1,1,1,0,1,8,Mild depression,1.0
19,u22,0,1,1,0,0,1,0,0,0,0,3,Minimal depression,0.0
20,u23,1,2,1,2,1,2,2,0,0,1,11,Moderate depression,2.0
21,u24,1,1,1,1,1,0,0,0,0,1,5,Mild depression,1.0
22,u27,0,0,2,1,0,0,2,0,0,1,5,Mild depression,1.0
23,u30,0,0,1,0,0,0,0,0,0,0,1,Minimal depression,0.0
24,u31,2,1,1,1,1,2,1,1,2,1,12,Moderate depression,2.0
25,u32,0,0,2,1,1,0,0,0,0,0,4,Minimal depression,0.0
26,u33,3,3,3,3,3,3,3,2,0,3,23,Severe depression,4.0
27,u34,0,0,1,0,1,1,0,0,0,0,3,Minimal depression,0.0
28,u35,1,1,1,1,1,1,1,0,0,1,7,Mild depression,1.0
29,u36,1,0,0,1,0,0,0,0,0,0,2,Minimal depression,0.0
30,u39,0,0,0,1,0,1,0,1,0,1,3,Minimal depression,0.0
31,u42,0,0,0,0,0,0,1,0,0,0,1,Minimal depression,0.0
32,u43,1,1,1,1,1,1,1,0,0,1,7,Mild depression,1.0
33,u44,0,0,0,1,0,0,0,0,0,1,1,Minimal depression,0.0
34,u45,1,1,2,1,1,1,0,0,0,0,7,Mild depression,1.0
35,u46,2,1,2,1,1,2,1,0,0,1,10,Moderate depression,2.0
36,u47,2,1,0,0,0,0,2,0,0,0,5,Mild depression,1.0
37,u49,0,0,0,1,1,0,0,0,0,1,2,Minimal depression,0.0
38,u50,0,1,0,2,1,1,0,1,1,0,7,Mild depression,1.0
39,u51,0,0,0,1,0,0,0,0,0,0,1,Minimal depression,0.0
40,u52,1,1,3,3,3,1,0,0,0,0,12,Moderate depression,2.0
41,u53,1,1,2,2,1,0,1,0,0,1,8,Mild depression,1.0
42,u56,0,0,0,2,0,0,0,0,0,0,2,Minimal depression,0.0
43,u57,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
44,u58,1,1,0,0,1,0,1,1,0,0,5,Mild depression,1.0
45,u59,0,0,1,2,1,0,0,1,0,0,5,Mild depression,1.0

,uid,pre_little_interest_or_pleasure_in_doing_things,pre_feeling_down_depressed_hopeless,pre_trouble_falling_or_staying_asleep_or_sleeping_too_much,pre_feeling_tired_or_having_little_energy,pre_poor_appetite_or_overeating,pre_feeling_bad_about_yourself_or_that_you_are_a_failure_or_have_let_yourself_or_your_family_down,pre_trouble_concentrating_on_things_such_as_reading_the_newspaper_or_watching_television,pre_moving_or_speaking_so_slowly_that_other_people_could_have_noticed_or_the_opposite_being_so_figety_or_restless_that_you_have_been_moving_around_a_lot_more_than_usual,pre_thoughts_that_you_would_be_better_off_dead_or_of_hurting_yourself,pre_response,pre_total_score,pre_depression_severity,post_little_interest_or_pleasure_in_doing_things,post_feeling_down_depressed_hopeless,post_trouble_falling_or_staying_asleep_or_sleeping_too_much,post_feeling_tired_or_having_little_energy,post_poor_appetite_or_overeating,post_feeling_bad_about_yourself_or_that_you_are_a_failure_or_have_let_yourself_or_your_family_down,post_trouble_concentrating_on_things_such_as_reading_the_newspaper_or_watching_television,post_moving_or_speaking_so_slowly_that_other_people_could_have_noticed_or_the_opposite_being_so_figety_or_restless_that_you_have_been_moving_around_a_lot_more_than_usual,post_thoughts_that_you_would_be_better_off_dead_or_of_hurting_yourself,post_response,post_total_score,post_depression_severity,pre_depression_class,post_depression_class
0,u00,0,1,0,1,0,0,0,0,0,0,2,Minimal depression,0,0,0,1,0,1,1,0,0,1,3,Minimal depression,0.0,0.0
1,u01,1,1,1,1,0,1,0,0,0,2,5,Mild depression,0,1,1,1,0,0,0,1,0,1,4,Minimal depression,1.0,0.0
2,u02,2,1,2,2,2,1,1,2,0,1,13,Moderate depression,2,0,0,1,1,0,1,0,0,1,5,Mild depression,2.0,1.0
3,u03,0,1,0,0,0,0,0,1,0,1,2,Minimal depression,1,1,0,1,0,1,0,0,0,1,4,Minimal depression,0.0,0.0
4,u04,1,1,0,1,1,1,1,0,0,1,6,Mild depression,1,1,1,1,1,2,1,0,0,1,8,Mild depression,1.0,1.0
5,u05,0,0,1,0,1,0,0,0,0,-1,2,Minimal depression,0,0,0,0,0,0,0,0,0,0,0,NaN,0.0,NaN
6,u07,1,1,0,1,2,1,1,0,0,0,7,Mild depression,1,1,2,2,2,0,0,0,0,1,8,Mild depression,1.0,1.0
7,u09,0,0,1,1,1,0,1,0,0,0,4,Minimal depression,0,0,0,0,1,1,0,0,0,0,2,Minimal depression,0.0,0.0
8,u10,0,0,0,0,0,0,0,0,0,-1,0,NaN,0,0,0,1,1,0,0,2,0,0,4,Minimal depression,NaN,0.0
9,u14,0,0,0,1,0,0,0,0,0,0,1,Minimal depression,0,0,1,1,1,0,0,0,0,-1,3,Minimal depression,0.0,0.0
10,u15,1,0,0,1,1,0,0,0,0,0,3,Minimal depression,0,0,1,0,0,0,0,0,0,0,1,Minimal depression,0.0,0.0
11,u16,1,1,1,0,0,3,0,0,0,1,6,Mild depression,1,2,2,3,2,2,0,0,0,1,12,Moderate depression,1.0,2.0
12,u17,1,1,3,3,3,1,0,1,0,1,13,Moderate depression,2,2,3,3,2,3,3,0,0,1,18,Moderately severe depression,2.0,3.0
13,u18,2,2,1,2,2,3,1,0,2,2,15,Moderately severe depression,2,2,1,2,2,1,1,0,1,1,12,Moderate depression,3.0,2.0
14,u19,1,1,0,0,1,1,0,0,1,1,5,Mild depression,0,1,0,0,1,1,0,0,1,0,4,Minimal depression,1.0,0.0
15,u20,1,1,1,1,1,1,1,1,0,1,8,Mild depression,1,2,1,1,1,2,0,0,0,1,8,Mild depression,1.0,1.0
16,u23,1,2,1,2,1,2,2,0,0,1,11,Moderate depression,2,3,3,2,2,3,2,2,2,2,21,Severe depression,2.0,4.0
17,u24,1,1,1,1,1,0,0,0,0,1,5,Mild depression,2,1,0,1,1,1,1,0,0,1,7,Mild depression,1.0,1.0
18,u27,0,0,2,1,0,0,2,0,0,1,5,Mild depression,1,1,0,2,0,1,2,0,0,1,7,Mild depression,1.0,1.0
19,u30,0,0,1,0,0,0,0,0,0,0,1,Minimal depression,0,0,0,0,0,0,0,0,0,-1,0,NaN,0.0,NaN
20,u31,2,1,1,1,1,2,1,1,2,1,12,Moderate depression,3,0,0,0,0,0,1,1,0,0,5,Mild depression,2.0,1.0
21,u32,0,0,2,1,1,0,0,0,0,0,4,Minimal depression,0,0,1,1,0,0,0,0,0,0,2,Minimal depression,0.0,0.0
22,u33,3,3,3,3,3,3,3,2,0,3,23,Severe depression,3,3,3,3,3,3,3,3,1,3,25,Severe depression,4.0,4.0
23,u34,0,0,1,0,1,1,0,0,0,0,3,Minimal depression,1,0,1,1,1,0,2,0,0,0,6,Mild depression,0.0,1.0
24,u35,1,1,1,1,1,1,1,0,0,1,7,Mild depression,1,1,0,1,1,1,1,1,0,0,7,Mild depression,1.0,1.0
25,u36,1,0,0,1,0,0,0,0,0,0,2,Minimal depression,0,0,0,1,0,0,0,0,0,1,1,Minimal depression,0.0,0.0
26,u42,0,0,0,0,0,0,1,0,0,0,1,Minimal depression,0,0,0,0,0,0,0,0,0,0,0,NaN,0.0,NaN
27,u43,1,1,1,1,1,1,1,0,0,1,7,Mild depression,0,0,1,1,1,0,1,0,0,1,4,Minimal depression,1.0,0.0
28,u44,0,0,0,1,0,0,0,0,0,1,1,Minimal depression,1,0,0,1,0,0,0,0,0,1,2,Minimal depression,0.0,0.0
29,u45,1,1,2,1,1,1,0,0,0,0,7,Mild depression,0,0,1,0,0,0,1,0,0,0,2,Minimal depression,1.0,0.0
30,u47,2,1,0,0,0,0,2,0,0,0,5,Mild depression,0,0,0,0,0,0,0,1,0,0,1,Minimal depression,1.0,0.0
31,u49,0,0,0,1,1,0,0,0,0,1,2,Minimal depression,3,0,2,2,1,0,0,0,0,1,8,Mild depression,0.0,1.0
32,u51,0,0,0,1,0,0,0,0,0,0,1,Minimal depression,0,0,0,0,0,0,0,0,0,-1,0,NaN,0.0,NaN
33,u52,1,1,3,3,3,1,0,0,0,0,12,Moderate depression,1,3,3,2,3,1,0,1,1,3,15,Moderately severe depression,2.0,3.0
34,u53,1,1,2,2,1,0,1,0,0,1,8,Mild depression,0,1,3,2,3,0,2,0,0,1,11,Moderate depression,1.0,2.0
35,u56,0,0,0,2,0,0,0,0,0,0,2,Minimal depression,0,0,0,2,0,0,1,0,0,1,3,Minimal depression,0.0,0.0
36,u58,1,1,0,0,1,0,1,1,0,0,5,Mild depression,0,1,0,2,2,1,1,1,0,0,8,Mild depression,1.0,1.0
37,u59,0,0,1,2,1,0,0,1,0,0,5,Mild depression,0,0,2,2,1,0,1,1,0,1,7,Mild depression,1.0,1.0

In [9]:
phq9_transformed.to_csv("./lstm_process_data/phq9_transformed_full.csv", index=False)
phq9_pre.to_csv("./lstm_process_data/phq9_transformed_pre.csv", index=False)
phq9_post.to_csv("./lstm_process_data/phq9_transformed_post.csv", index=False)